global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "excalidraw-http"
    static_configs:
      - targets: ["host.docker.internal:3001"]
    metrics_path: /metrics
  - job_name: "excalidraw-ws"
    static_configs:
      - targets: ["host.docker.internal:8081"]
    metrics_path: /metrics
